#!/usr/bin/env bash

# this is a simple config for herbstluftwm
# tag: workspace, thingies on top
# frame: 'mega' window, thing that can contain miniwindows
# theme: actual window, thing like gtk3 theme. name of app and the like.
# 	multiple of these can be in one frame

# Color variables =====
Cyan='#07DAE2'
LightGray='#5E5E5E'
DarkGray='#313131'
White='#F5F5F5'
Magenta='#D00281'
# =====================

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#6c6c6c' # sets background color, overwrites normal background

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# Custom bindings for ease of use
hc keybind $Mod-Return spawn alacritty --config-file $HOME/.config/mikuflavor/alacritty.toml
hc keybind $Mod-d spawn rofi -show combi -modes combi -combi-modes "window,drun,run" \
                             -config $HOME/.config/mikuflavor/config.rasi
hc keybind $Mod-w spawn firefox
hc keybind $Mod-n spawn nemo

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
# vim style stuff I see
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Workspaces
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Theme
# ===============================================
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# Frames
hc set frame_border_active_color $Magenta # Active Frame
hc set frame_border_normal_color $White # Inactive Frame
hc set frame_border_width 3 
hc set frame_gap 15 # Separation between frames
hc set frame_bg_transparent on # Makes BG transparent
# Disabled here
hc set frame_bg_normal_color $DarkGray # not selected
hc set frame_bg_active_color $Magenta # background of active
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_transparent_width 0 # Confusing

# All of the following are disabled for the style
hc attr theme.title_height 15
hc attr theme.title_when never
hc attr theme.title_font 'Ubuntu Mono:pixelsize=16'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_color $Cyan # applies only to window, active window
hc attr theme.title_depth 5  # space below the title's baseline
hc attr theme.active.color $LightGray # current active window, or miniframe
hc attr theme.normal.color $DarkGray # color of non active window, miniframe
hc attr theme.urgent.color 'red'
hc attr theme.tab_color 'yellow' # idk
hc attr theme.active.tab_color 'red'
hc attr theme.active.tab_outer_color ''
hc attr theme.active.tab_title_color ''
hc attr theme.normal.title_color $White # color of non active window AND miniframe
hc attr theme.inner_color $Cyan
hc attr theme.border_width 0 # border around each theme/window in frame
hc attr theme.inner_width 0 # changes stuff between window frame and content
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color ''
hc attr theme.urgent.inner_color ''
hc attr theme.normal.inner_color ''
hc attr theme.tiling.outer_width 0 # removes little black line outside of miniwindow
hc attr theme.background_color ''

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

hc set window_gap 15 # borders between themes/windows in frame 
hc set frame_padding 0 # between theme/window AND frame, added on top of windowgap
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
# ===============================================

# Here you can add rules, i.e. default behaviors that
# can help your workflow
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
hc detect_monitors
# commented out so panel and polybar dont overlap
# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
# done

# Things to run on startup
feh --bg-fill $HOME/.config/mikuflavor/wp_1.jpg
hc spawn picom --config $HOME/.config/mikuflavor/picom.conf
setxkbmap -layout us,cz,at
wal -R
hc spawn polybar -r -c $HOME/.config/mikuflavor/config.ini
