alacritty:
  background: "#334C4C"
  foreground: "#BDBDBD"
  magenta: "#8D1B1B"
  blue: "#5E6969"
  black: "#1A2626"
  red: "#8D1B1B"
  cyan: "#5E9E9E"
  yellow: "#C4A24E"
  white: "#BDBDBD"
  light_gray: "#5E6969"
  warning: "#C4A24E"
  highlight: "#5E9E9E"

rofi:
  alert: "#8D1B1B"
  accent: "#5E6969"
  background: "#334C4C"
  light_background: "#3E5A5A"
  foreground: "#BDBDBD"
  foreground_alt: "#5E9E9E"
  muted: "#5E6969"

polybar:
  background: "#334C4C"
  light_background: "#5E6969"
  foreground: "#BDBDBD"
  foreground_alt: "#5E9E9E"
  primary: "#8D1B1B"
  secondary: "#5E9E9E"
  alert: "#8D1B1B"
  muted: "#5E6969"
  border: "#1A2626"
  warning: "#C4A24E"

hlwm:
  title_color: "#5E9E9E"
  active_color: "#5E6969"
  inactive_color: "#334C4C"
  border_highlight: "#BDBDBD"
  frame_active_color: "#8D1B1B"
  urgent_color: "#8D1B1B"
  tab_color: "#C4A24E"
  outer_shadow: "#1A2626"
  root_background: "#3E5A5A"
