palette:
  cyan: "#07DAE2"
  light_gray: "#5E5E5E"
  dark_gray: "#313131"
  white: "#F5F5F5"
  magenta: "#D00281"
  background: "#F5F5F5"
  light_background: "#E0E0E0"
  foreground: "#606060"
  foreground_alt: "#586875"
  blue: "#268BD2"
  red: "#DC322F"
  warning: "#F0C674"
  muted: "#707880"
  root_background: "#6C6C6C"
  black: "#000000"
  yellow: "#FFFF00"
